name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake

  docker:
    runs-on: ubuntu-latest
    name: Build Docker Container
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: searls
          password: ${{ secrets.CH_PAT }}
      - name: Calculate Docker tags
        id: tags
        run: |
          echo "tags<<EOTAGS" >> "$GITHUB_OUTPUT"
          echo "ghcr.io/searls/feed2gram:${{ github.event.pull_request.head.sha || github.sha }}" >> "$GITHUB_OUTPUT"
          if [ "${{ github.ref_name }}" == "${{ github.event.repository.default_branch }}" ]; then
            echo "ghcr.io/searls/feed2gram:latest" >> "$GITHUB_OUTPUT"
          fi
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            GIT_TAG=${GITHUB_REF#refs/tags/v}
            echo "ghcr.io/searls/feed2gram:${GIT_TAG}" >> "$GITHUB_OUTPUT"
          fi
          echo "EOTAGS" >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.tags.outputs.tags }}
